name: Nest1
description: Nest 1

inputs:
  test:
    description: 'Test input'
    default: 'default'

runs:
  using: composite
  steps:
    - uses: srz-zumix/post-run-action@v2
      with:
        post-run: |
          echo "test=${{ inputs.test }}"
    - uses: suzuki-shunsuke/lock-action@latest
      with:
        mode: lock
        key: ${{ inputs.test }}
        post_unlock: "true"
