name: Nest2
description: Nest 2

inputs:
  test:
    description: 'Test input'
    default: 'default'

runs:
  using: composite
  steps:
    - uses: ./.github/actions/nest2
      with:
        test: ${{ inputs.test }}
