name: Ignore Self
on:
  pull_request:
    paths-ignore:
      - .github/**
      - "!.github/workflows/paths-ignore-self.yml"

jobs:
  ignore-self-do:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
