name: reviewdog
on:
  pull_request:

jobs:
  jflint:
    name: jflint
    runs-on: ubuntu-latest
    services:
      jenkins:
        image: ghcr.io/srz-zumix/action-jenkins
        ports:
          - 8080:8080
          - 50000:50000
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
    env:
      JENKINS_URL: http://localhost:8080
      JENKINS_USER: test
      JENKINS_PASSWORD: pass
      TARGET_BRANCH: ${{ github.base_ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: reviewdog/action-setup@v1
      - run: npm install
      # git diff をするためにターゲットブランチをフェッチする必要がある
      - name: 'Fetch'
        run: git fetch --depth 1 origin ${TARGET_BRANCH}
      - name: lint
        # shell: bash -e -o pipefail {0}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in $(git diff origin/${TARGET_BRANCH} HEAD --diff-filter=AM --name-only -- "*.Jenkinsfile") ; do
            echo "${file}"
            npx jflint -j "${JENKINS_URL}" -u "${JENKINS_USER}" -p "${JENKINS_PASSWORD}" "${file}" 2>&1 \
              | sed -e "s|WorkflowScript:|${file}:|g" | tee -a log.txt
          done
          if [ -e log.txt ]; then
            cat log.txt | reviewdog -reporter=github-pr-review -name="jflint" -efm="%f: %l: %m"
            rm -f log.txt
          fi
