name: reviewdog
on:
  pull_request:

jobs:
  jflint:
    name: jflint
    runs-on: ubuntu-latest
    environment: dockerhub
    services:
      jenkins:
        # image: ghcr.io/srz-zumix/action-jenkins
        # credentials:
        #   username: ${{ github.repository_owner }}
        #   password: ${{ secrets.GHCR_PAT }}
        image: jenkins/jenkins:lts-jdk11
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
          - 8080:8080
          - 50000:50000
    env:
      JENKINS_URL: http://localhost:8080
      JENKINS_USER: test
      JENKINS_PASSWORD: pass
      TARGET_BRANCH: ${{ github.base_ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: reviewdog/action-setup@v1
      - run: npm install
      # git diff をするためにターゲットブランチをフェッチする必要がある
      - name: 'Fetch'
        run: git fetch --depth 1 origin ${TARGET_BRANCH}
      # サービスの Jenkins が起動するのを待つ
      - name: Wait Launch Jenkins
        run: |
          until docker logs "${{ job.services.jenkins.id }}" 2>&1 | grep "Jenkins is fully up and running"; do
            sleep 30 | echo "waiting..."
          done
          docker logs "${{ job.services.jenkins.id }}"
      # Jenkins のプラグインインストール
      - name: Install Jenkins Plugins
        run: |
          docker cp ./JenkinsPlugins.txt "${{ job.services.jenkins.id }}":/home/JenkinsPlugins.txt
          docker exec "${{ job.services.jenkins.id }}" jenkins-plugin-cli --verbose --plugin-file /home/JenkinsPlugins.txt
      - name: Reload Jenkins
        run: |
          wget ${JENKINS_URL}/jnlpJars/jenkins-cli.jar
          java -jar jenkins-cli.jar -s "${JENKINS_URL}" reload-configuration
          sleep 120
      - name: lint
        shell: bash -e -o pipefail {0}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in $(git diff origin/${TARGET_BRANCH} HEAD --diff-filter=AM --name-only -- "*Jenkinsfile") ; do
            echo "${file}"
            npx jflint -j "${JENKINS_URL}" -u "${JENKINS_USER}" -p "${JENKINS_PASSWORD}" "${file}" 2>&1 \
              | sed -e "s|WorkflowScript:|${file}:|g" | tee -a log.txt
          done
          if [ -e log.txt ]; then
            cat log.txt | reviewdog -reporter=github-pr-review -name="jflint" -efm="%f: %l: %m"
            rm -f log.txt
          fi
