name: Secrets outputs
on:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      SECRET_VALUE: ${{ steps.out.outputs.test }}
    steps:
      - id: out
        run: |
          echo "test=${{ secrets.TEST_SECRET }}" >> "${GITHUB_OUTPUT}"
      - run: |
          echo "${{ steps.out.outputs.test }}"

  secrets-outputs-job:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.prepare.outputs.SECRET_VALUE }}"
