name: "Check"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited # for change base
      - labeled
      - unlabeled

jobs:
  base_branch_label_cehck:
    runs-on: ubuntu-latest
    if: >
      github.event.action != 'edited' ||
      github.event.changes.base
    steps:
      - run: echo ${LABELS} | grep ${GITHUB_BASE_REF}
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}

